#password should be in vault and gets replaced at deployment thus not checked-in repository 
version: "3.2"
services: 
    web:
        build: .
        container_name: api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - 'DB_Conn=Server=sqlserver;Database=CoreAPI;User Id=sa;Password=CoreAPI@2022;'
            - ASPNETCORE_URLS=http://+:9122
        expose:
            - "9122"
        ports:
            - "5000:9122"
        volumes:
            - type: bind
              source: C:\App\Images
              target: /usr/share/Images
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        container_name: sqlserver
        environment:
            SA_PASSWORD: "CoreAPI@2022"
            ACCEPT_EULA: "Y"
        volumes:
            - type: bind
              source: C:\MSSQL\datafiles
              target: /var/opt/sqlserver
            - type: bind
              source: C:\MSSQL\system
              target: /var/opt/mssql/data
        